# Generated by Django 4.2.4 on 2023-09-22 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('accesorio_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('aprendiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=2)),
                ('numero_documento', models.CharField(max_length=20)),
                ('ficha_aprendiz', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('equipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255)),
                ('contraseña', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('prestamo_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateTimeField()),
                ('fecha_devolucion', models.DateTimeField()),
                ('estado_prestamo', models.CharField(max_length=50)),
                ('accesorio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.accesorio')),
                ('aprendiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.aprendiz')),
                ('equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.equipo')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.usuario')),
            ],
            options={
                'db_table': 'Prestamo',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('inventario_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('accesorio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.accesorio')),
                ('equipo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('devolucion_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_devolucion', models.DateTimeField(null=True)),
                ('accesorio_devuelto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.accesorio')),
                ('equipo_devuelto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.equipo')),
                ('prestamo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.prestamo')),
            ],
        ),
    ]
