# Generated by Django 4.2.4 on 2023-09-19 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prestamo',
            table='tblPrestamos',
        ),
    ]
