# Generated by Django 4.2.4 on 2023-09-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_prestamo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prestamo',
            table='Prestamo',
        ),
    ]
