# Generated by Django 4.2.4 on 2023-09-22 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_devolucion_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='accesorio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.accesorio'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='equipo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.equipo'),
        ),
    ]
