# Generated by Django 4.2.4 on 2023-09-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_accesorio_estado_equipo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorio',
            name='estado',
            field=models.CharField(blank=True, default='Disponible', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(blank=True, default='Disponible', max_length=50, null=True),
        ),
    ]
